import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying with account:", deployer.address);

  // 1. Deploy MockUSDC — mint initial supply to deployer
  const MockUSDC = await ethers.getContractFactory("MockUSDC");
  const usdc = await MockUSDC.deploy(deployer.address);
  await usdc.waitForDeployment();
  const usdcAddress = await usdc.getAddress();
  console.log("MockUSDC deployed to:", usdcAddress);

  // 2. Deploy SplitVault with USDC address and oracle (deployer)
  const oracleAddress = deployer.address;
  const SplitVault = await ethers.getContractFactory("SplitVault");
  const vault = await SplitVault.deploy(usdcAddress, oracleAddress);
  await vault.waitForDeployment();
  const vaultAddress = await vault.getAddress();
  console.log("SplitVault deployed to:", vaultAddress);
  console.log("Oracle address:", oracleAddress);

  // 3. Distribute USDC to test accounts for demo
  const signers = await ethers.getSigners();
  const testAmount = 100_000n * 10n ** 6n; // 100,000 USDC each
  for (let i = 1; i < Math.min(signers.length, 5); i++) {
    await usdc.mint(signers[i].address, testAmount);
    console.log(`Minted ${ethers.formatUnits(testAmount, 6)} USDC to ${signers[i].address}`);
  }

  // 4. Pre-approve vault for deployer (convenient for demo)
  await usdc.approve(vaultAddress, ethers.MaxUint256);
  console.log("Deployer approved vault for unlimited USDC spending");

  // 5. Write .env.local for the Next.js app
  const oraclePrivateKey =
    "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80";

  const envContent = [
    "# Auto-generated by deploy-local.ts",
    `NEXT_PUBLIC_VAULT_ADDRESS=${vaultAddress}`,
    `NEXT_PUBLIC_USDC_ADDRESS=${usdcAddress}`,
    `ORACLE_PRIVATE_KEY=${oraclePrivateKey}`,
    `BASE_SEPOLIA_RPC=http://127.0.0.1:8545`,
    "",
  ].join("\n");

  const envPath = path.resolve(__dirname, "../../.env.local");
  fs.writeFileSync(envPath, envContent);
  console.log(`\n.env.local written to: ${envPath}`);
  console.log("\n--- Environment Variables ---");
  console.log(envContent);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
