import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

// Agent addresses from shapley.ts — these are Hardhat's default accounts [2], [3], [1]
const AGENT_ADDRESSES = [
  "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC", // researcher_a (account #2)
  "0x90F79bf6EB2c4f870365E785982E1f101E93b906", // researcher_b (account #3)
  "0x70997970C51812dc3A010C7d01b50e0d17dc79C8", // synthesizer  (account #1)
];

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying with account:", deployer.address);

  // Deploy SplitVault — deployer is the oracle
  const oracleAddress = deployer.address;
  const SplitVault = await ethers.getContractFactory("SplitVault");
  const vault = await SplitVault.deploy(oracleAddress);
  await vault.waitForDeployment();

  const vaultAddress = await vault.getAddress();
  console.log("SplitVault deployed to:", vaultAddress);
  console.log("Oracle address:", oracleAddress);

  // Fund agent addresses so they can receive ETH settlements
  // (Hardhat local accounts already have ETH, but the agent addresses
  // need to be able to receive — which they can as EOAs, no funding needed.
  // However, we log which accounts map to agents for clarity.)
  console.log("\nAgent addresses (pre-funded by Hardhat node):");
  for (const addr of AGENT_ADDRESSES) {
    const balance = await ethers.provider.getBalance(addr);
    console.log(`  ${addr}: ${ethers.formatEther(balance)} ETH`);
  }

  // Write .env.local for the Next.js app
  // Hardhat account #0 private key (deployer/oracle)
  const oraclePrivateKey =
    "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80";

  const envContent = [
    "# Auto-generated by deploy-local.ts",
    `NEXT_PUBLIC_VAULT_ADDRESS=${vaultAddress}`,
    `ORACLE_PRIVATE_KEY=${oraclePrivateKey}`,
    `BASE_SEPOLIA_RPC=http://127.0.0.1:8545`,
    "",
  ].join("\n");

  const envPath = path.resolve(__dirname, "../../.env.local");
  fs.writeFileSync(envPath, envContent);
  console.log(`\n.env.local written to: ${envPath}`);
  console.log("\n--- Environment Variables ---");
  console.log(envContent);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
