/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SplitVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createTask"
      | "getTask"
      | "oracle"
      | "settle"
      | "submitSplit"
      | "taskCount"
      | "taskIds"
      | "tasks"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Settled" | "SplitSubmitted" | "TaskCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createTask",
    values: [BytesLike, AddressLike[]]
  ): string;
  encodeFunctionData(functionFragment: "getTask", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "settle", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "submitSplit",
    values: [BytesLike, BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "taskCount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "taskIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "tasks", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "createTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "settle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "taskCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "taskIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tasks", data: BytesLike): Result;
}

export namespace SettledEvent {
  export type InputTuple = [
    taskId: BytesLike,
    agents: AddressLike[],
    payouts: BigNumberish[]
  ];
  export type OutputTuple = [
    taskId: string,
    agents: string[],
    payouts: bigint[]
  ];
  export interface OutputObject {
    taskId: string;
    agents: string[];
    payouts: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SplitSubmittedEvent {
  export type InputTuple = [taskId: BytesLike, shares: BigNumberish[]];
  export type OutputTuple = [taskId: string, shares: bigint[]];
  export interface OutputObject {
    taskId: string;
    shares: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCreatedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    payer: AddressLike,
    agents: AddressLike[],
    totalAmount: BigNumberish
  ];
  export type OutputTuple = [
    taskId: string,
    payer: string,
    agents: string[],
    totalAmount: bigint
  ];
  export interface OutputObject {
    taskId: string;
    payer: string;
    agents: string[];
    totalAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SplitVault extends BaseContract {
  connect(runner?: ContractRunner | null): SplitVault;
  waitForDeployment(): Promise<this>;

  interface: SplitVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createTask: TypedContractMethod<
    [taskId: BytesLike, agents: AddressLike[]],
    [void],
    "payable"
  >;

  getTask: TypedContractMethod<
    [taskId: BytesLike],
    [
      [string, string[], bigint, bigint[], boolean, boolean] & {
        payer: string;
        agents: string[];
        totalAmount: bigint;
        shares: bigint[];
        splitSubmitted: boolean;
        settled: boolean;
      }
    ],
    "view"
  >;

  oracle: TypedContractMethod<[], [string], "view">;

  settle: TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;

  submitSplit: TypedContractMethod<
    [taskId: BytesLike, shares: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  taskCount: TypedContractMethod<[], [bigint], "view">;

  taskIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  tasks: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, boolean, boolean] & {
        taskId: string;
        payer: string;
        totalAmount: bigint;
        splitSubmitted: boolean;
        settled: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createTask"
  ): TypedContractMethod<
    [taskId: BytesLike, agents: AddressLike[]],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getTask"
  ): TypedContractMethod<
    [taskId: BytesLike],
    [
      [string, string[], bigint, bigint[], boolean, boolean] & {
        payer: string;
        agents: string[];
        totalAmount: bigint;
        shares: bigint[];
        splitSubmitted: boolean;
        settled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "oracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "settle"
  ): TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitSplit"
  ): TypedContractMethod<
    [taskId: BytesLike, shares: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "taskCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "taskIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "tasks"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, boolean, boolean] & {
        taskId: string;
        payer: string;
        totalAmount: bigint;
        splitSubmitted: boolean;
        settled: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "Settled"
  ): TypedContractEvent<
    SettledEvent.InputTuple,
    SettledEvent.OutputTuple,
    SettledEvent.OutputObject
  >;
  getEvent(
    key: "SplitSubmitted"
  ): TypedContractEvent<
    SplitSubmittedEvent.InputTuple,
    SplitSubmittedEvent.OutputTuple,
    SplitSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCreated"
  ): TypedContractEvent<
    TaskCreatedEvent.InputTuple,
    TaskCreatedEvent.OutputTuple,
    TaskCreatedEvent.OutputObject
  >;

  filters: {
    "Settled(bytes32,address[],uint256[])": TypedContractEvent<
      SettledEvent.InputTuple,
      SettledEvent.OutputTuple,
      SettledEvent.OutputObject
    >;
    Settled: TypedContractEvent<
      SettledEvent.InputTuple,
      SettledEvent.OutputTuple,
      SettledEvent.OutputObject
    >;

    "SplitSubmitted(bytes32,uint256[])": TypedContractEvent<
      SplitSubmittedEvent.InputTuple,
      SplitSubmittedEvent.OutputTuple,
      SplitSubmittedEvent.OutputObject
    >;
    SplitSubmitted: TypedContractEvent<
      SplitSubmittedEvent.InputTuple,
      SplitSubmittedEvent.OutputTuple,
      SplitSubmittedEvent.OutputObject
    >;

    "TaskCreated(bytes32,address,address[],uint256)": TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
    TaskCreated: TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
  };
}
